version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8003:8080"
    volumes:
      - ./openapi.yaml:/open-api.yaml
    environment:
      SWAGGER_JSON: /open-api.yaml
  postgres:
    image: postgres:latest
    container_name: flowy_postgres
    restart: always
    environment:
      POSTGRES_USER: flowy
      POSTGRES_PASSWORD: flowy
      POSTGRES_DB: flowy
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
